/* autogenerated by Processing revision 1292 on 2023-04-22 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class sketch_drawing extends PApplet {

int p = 50; 
int k = 100;
PFont font;
PGraphics foreground;
int g;
int n;


public void setup() {

/* size commented out by preprocessor */;
/* pixelDensity commented out by preprocessor */;
/* smooth commented out by preprocessor */;
font = createFont("Roboto-Bold", 114);
foreground = createGraphics(width, height);   

}

public void keyPressed() {
  foreground.beginDraw();
  foreground.textSize(144);
  foreground.textFont(font);


  float textWidth = foreground.textWidth(key); 
  if (p + textWidth > width) { 
    p = 50; 
    k += 100; 
  }
  foreground.text(key, p, k); 
  p += textWidth;
   foreground.endDraw();
 } 
 

public void draw() {
image(foreground, 0, 0);
int z = color(0, 126, 255, 0);
int c = color(random(0,255), random(0,255),random(0,255));

 if (keyPressed == true) {
 
  // A random squares
  if (key == 'a' || key == 'A') {
     strokeWeight(0);
     fill(c);
     rect(random(0,1920), random(0,1080), 50, 50) ;
   } 
  
  
  // B Bezier
  if (key == 'b' || key == 'B') {
     fill(z);
     strokeWeight(1);
     stroke(random(0,155));
     for (int n = 0; n < 1; n++) {
    float x1 = random(width);
    float y1 = random(height);
    float x2 = random(width);
    float y2 = random(height);
    float cx1 = random(width);
    float cy1 = random(height);
    float cx2 = random(width);
    float cy2 = random(height);
    bezier(x1, y1, cx1, cy1, cx2, cy2, x2, y2);
  }      } 
  
  // C rando colour
  if (key == 'c' || key == 'C') {
    fill(c);
  } 
  
  // D Delta Triangle
   
   if (key == 'd' || key == 'D') {
   strokeWeight(3);
   fill(z);
   triangle(random(0,1920), random(0,1080), random(0,1920), random(0,1080), random(0,1920), random(0,1080));
  }
  
  // E Elipse
  
   if (key == 'e' || key == 'E') {
   fill(c); // Problem C is always random and not a normal colour at all???
   strokeWeight(0);
   ellipse(random(0,1920), random(0,1080), random(10,100), random(50,100));
  } 
  
  // F Elipse
  
   if (key == 'f' || key == 'F') {
   fill(c); // Problem C is always random and not a normal colour at all???
   ellipse(random(0,1920), random(0,1080), random(10,100), random(50,100));
   }
 // G Gradient
  
   if (key == 'g' || key == 'G') {
  
 int c1 = color(random(255), random(255), random(255));
 int c2 = color(random(255), random(255), random(255));

    for (int g = 0; g < height; g++) {
      float pct = map(g, 0, height, 0, 1);
      int c3 = lerpColor(c1, c2, pct);
      stroke(c3);
      line(1, g, width, g);
    } 
  }
  
 // H   nochmal mehr am grid arbeiten
  if (key == 'h' || key == 'H') {
    stroke(c);
      int gridSize = 10;
      int spacing = width/gridSize;
  
  for (int x = 0; x < width; x += spacing) {
    for (int y = 0; y < height; y += spacing) {
      if (random(20) < 1) {
        line(x, y, x + spacing, y + spacing);
      } else {
        line(x + spacing, y, x, y + spacing);
      }
    }
  }
  } 
  
  // I Invert 
 
 if (key == 'i' || key == 'I') {
  PImage img = get();
  for (int i = 0; i < img.pixels.length; i++) {
    img.pixels[i] = color(255 - red(img.pixels[i]), 255 - green(img.pixels[i]), 255 - blue(img.pixels[i]));
  }
  img.updatePixels();
  image(img, 0, 0);
    }
 
 // J  
 
 if (key == 'j' || key == 'J') {
   
 
   
 }
 
  // N Newtriangle
  
if (key == 'N' || key == 'N') {
    
  
    }   
  // S Sine 
 
 if (key == 's' || key == 'S') {
  stroke(0);
  strokeWeight(2);
  noFill();

  // Generate random values for the sine wave
  float amplitude = random(10, 800);
  float frequency = random(0.02f, 0.05f);
  float phase = random(TWO_PI);

  // Draw the sine wave
  beginShape();
  for (float x = 0; x < width; x += 10) {
    float y = height / 2 + amplitude * sin(frequency * x + phase);
    vertex(x, y);
  }
  endShape();
 }
  }}  
  


  public void settings() { size(1080, 1080);
pixelDensity(1);
smooth(); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "sketch_drawing" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
